import type { LevelDef } from "./types";
import walyBg from "@/assets/waly.jpg";
import park1Bg from "@/assets/park1.jpg";
import park2Bg from "@/assets/park2.jpg";
import roofBg from "@/assets/level-roof.jpg";
import blokBg from "@/assets/level-blok.jpg";

const W = 1600;
const H = 900;

export const LEVELS: LevelDef[] = [
  {
    id: "1",
    slug: "waly-chrobrego",
    title: "Wały Chrobrego",
    subtitle: "Wieczorny spacer nad Odrą",
    background: walyBg,
    width: 2560,
    height: 1787,
    spawn: { x: 1200, y: 1680 },
    ambient: "night",
    ambientFx: "motes",
    intro: "Wieczorne światła Wałów Chrobrego migoczą nad Odrą. Edek wymyka się na spacer.",
    objective: "Znajdź piłeczkę i smakołyk, potem wejdź przez bramę do baszty.",
    unlockHint: "Dostępne od początku — pierwsza wyprawa Edka.",
    quests: [
      { id: "q1-ball", kind: "collect", itemId: "ball", count: 1, label: "Znajdź piłeczkę na promenadzie" },
      { id: "q1-treat", kind: "collect", itemId: "treat", count: 1, label: "Znajdź smakołyk przy latarni" },
      { id: "q1-entrance", kind: "reach", objId: "entrance", label: "Wejdź przez bramę do baszty" },
    ],
    pointLight: { x: 448, y: 1632, color: "rgba(255,180,80,0.85)", intensity: 0.7 },
    objects: [
      { id: "rotunda", kind: "obstacle", rect: { x: 0, y: 619, w: 1120, h: 950 } },
      { id: "wall-right", kind: "obstacle", rect: { x: 1440, y: 1032, w: 1120, h: 538 } },
      { id: "tree", kind: "obstacle", rect: { x: 1152, y: 448, w: 288, h: 544 } },
      { id: "i-ball", kind: "item", itemId: "ball", rect: { x: 672, y: 1648, w: 80, h: 80 } },
      { id: "i-treat", kind: "item", itemId: "treat", rect: { x: 1840, y: 1648, w: 80, h: 80 } },
      { id: "entrance", kind: "goal", icon: "🏰", rect: { x: 2080, y: 1600, w: 192, h: 144 },
        requires: { ball: 1, treat: 1 }, message: "Brama otwarta! Edek wchodzi do baszty pełnej tajemnic." },
    ],
  },
  {
    id: "2",
    slug: "park-kasprowicza",
    title: "Park Kasprowicza",
    subtitle: "Pomnik Czynu Polaków",
    background: park1Bg,
    width: 1560,
    height: 1560,
    spawn: { x: 780, y: 1495 },
    ambient: "day",
    ambientFx: "petals",
    intro: "Słońce grzeje klomby przy Pomniku Czynu Polaków. Edek węszy wśród kwiatów.",
    objective: "Znajdź 3 myszki, pogadaj z wiewiórką, znajdź wyjście w głąb alei.",
    unlockHint: "Odblokowane po wieczornym spacerze na Wałach Chrobrego (Poziom 1).",
    quests: [
      { id: "q2-mice", kind: "collect", itemId: "mouse", count: 3, label: "Znajdź 3 myszki na trawnikach parku" },
      { id: "q2-squirrel", kind: "talk", objId: "squirrel", label: "Pogadaj z wiewiórką przy pomniku" },
      { id: "q2-gate", kind: "reach", objId: "gate", label: "Znajdź wyjście w głąb alei" },
    ],
    objects: [
      { id: "trees", kind: "obstacle", rect: { x: 0, y: 0, w: 1560, h: 325 } },
      { id: "monument", kind: "obstacle", rect: { x: 585, y: 325, w: 429, h: 572 } },
      { id: "flowerbed-l", kind: "obstacle", rect: { x: 0, y: 1040, w: 546, h: 520 } },
      { id: "flowerbed-r", kind: "obstacle", rect: { x: 1014, y: 1040, w: 546, h: 520 } },
      { id: "m1", kind: "item", itemId: "mouse", rect: { x: 195, y: 780, w: 65, h: 65 } },
      { id: "m2", kind: "item", itemId: "mouse", rect: { x: 1365, y: 780, w: 65, h: 65 } },
      { id: "m3", kind: "item", itemId: "mouse", rect: { x: 780, y: 1235, w: 65, h: 65 } },
      { id: "squirrel", kind: "npc", npcId: "squirrel", icon: "🐿️", rect: { x: 208, y: 364, w: 104, h: 104 },
        message: "Cześć Edku! Weź ten kłębek — przyda Ci się." },
      { id: "gate", kind: "goal", icon: "🚪", rect: { x: 1079, y: 364, w: 117, h: 117 },
        requires: { mouse: 3, yarn: 1 }, message: "Aleja prowadzi dalej. Czas na złote liście!" },
    ],
  },
  {
    id: "3",
    slug: "aleja-kasztanowa",
    title: "Aleja Kasztanowa",
    subtitle: "Złota jesień w Parku Kasprowicza",
    background: park2Bg,
    width: 2560,
    height: 1920,
    spawn: { x: 1600, y: 1680 },
    ambient: "day",
    ambientFx: "petals",
    intro: "Złota aleja szeleści pod łapkami. Edek brnie przez stertę liści.",
    objective: "Zbierz 3 złote liście i odpocznij na ławce.",
    unlockHint: "Odblokowane po zwiedzeniu Pomnika Czynu Polaków (Poziom 2).",
    quests: [
      { id: "q3-leaves", kind: "collect", itemId: "leaf", count: 3, label: "Zbierz 3 złote liście" },
      { id: "q3-bench", kind: "reach", objId: "bench", label: "Zwiń się w kłębek na ławce" },
    ],
    objects: [
      { id: "tree-center", kind: "obstacle", rect: { x: 1024, y: 0, w: 352, h: 1520 } },
      { id: "trees-right", kind: "obstacle", rect: { x: 1920, y: 0, w: 640, h: 1040 } },
      { id: "trees-left-bg", kind: "obstacle", rect: { x: 0, y: 0, w: 320, h: 880 } },
      { id: "i-leaf1", kind: "item", itemId: "leaf", rect: { x: 480, y: 1440, w: 80, h: 80 } },
      { id: "i-leaf2", kind: "item", itemId: "leaf", rect: { x: 2080, y: 1440, w: 80, h: 80 } },
      { id: "i-leaf3", kind: "item", itemId: "leaf", rect: { x: 1520, y: 1120, w: 80, h: 80 } },
      { id: "bench", kind: "goal", icon: "🍂", rect: { x: 896, y: 1520, w: 288, h: 160 },
        requires: { leaf: 3 }, message: "Edek zwija się w kłębek na ławce, otoczony jesiennymi liśćmi." },
    ],
  },
  {
    id: "4",
    slug: "dach",
    title: "Dach nocą",
    subtitle: "Pod gwiazdami",
    background: roofBg,
    width: W,
    height: H,
    spawn: { x: 200, y: 800 },
    ambient: "night",
    ambientFx: "stars",
    intro: "Powietrze jest chłodne. Księżyc wisi tuż obok.",
    objective: "Zbierz 5 spadających gwiazd i spotkaj się z przyjacielem.",
    unlockHint: "Odblokowane po jesiennym spacerze Aleją Kasztanową (Poziom 3).",
    quests: [
      { id: "q4-stars", kind: "collect", itemId: "star", count: 5, label: "Zbierz 5 spadających gwiazd" },
      { id: "q4-friend", kind: "reach", objId: "friend", label: "Znajdź przyjaciela na dachu" },
    ],
    objects: [
      { id: "chimney1", kind: "obstacle", rect: { x: 480, y: 240, w: 180, h: 200 } },
      { id: "chimney2", kind: "obstacle", rect: { x: 1180, y: 540, w: 180, h: 220 } },
      { id: "vane", kind: "obstacle", rect: { x: 900, y: 380, w: 120, h: 200 } },
      { id: "s1", kind: "item", itemId: "star", rect: { x: 300, y: 200, w: 50, h: 50 } },
      { id: "s2", kind: "item", itemId: "star", rect: { x: 800, y: 100, w: 50, h: 50 } },
      { id: "s3", kind: "item", itemId: "star", rect: { x: 1300, y: 250, w: 50, h: 50 } },
      { id: "s4", kind: "item", itemId: "star", rect: { x: 700, y: 700, w: 50, h: 50 } },
      { id: "s5", kind: "item", itemId: "star", rect: { x: 1450, y: 800, w: 50, h: 50 } },
      { id: "friend", kind: "goal", icon: "🐈", rect: { x: 1400, y: 400, w: 100, h: 100 },
        requires: { star: 5 }, message: "Przyjaciel mruczy: 'Wiedziałem, że dasz radę, Edek!'" },
    ],
  },
  {
    id: "5",
    slug: "blokowisko",
    title: "Blokowisko",
    subtitle: "Wielka wyprawa w Szczecinie",
    background: blokBg,
    width: W,
    height: H,
    spawn: { x: 150, y: 800 },
    ambient: "day",
    ambientFx: "motes",
    intro: "Ktoś zostawił okno na klatce uchylone. Edek zeskakuje na podwórko — ale skąd tu wraca do domu?",
    objective: "Znajdź 3 smakołyki, pogadaj z gołębiem, wróć do klatki schodowej.",
    unlockHint: "Odblokowane po powrocie z dachu (Poziom 4).",
    quests: [
      { id: "q5-treats", kind: "collect", itemId: "treat", count: 3, label: "Znajdź 3 smakołyki na podwórku" },
      { id: "q5-pigeon", kind: "talk", objId: "pigeon", label: "Pogadaj z gołębiem po piórko" },
      { id: "q5-entrance", kind: "reach", objId: "entrance", label: "Wróć do klatki schodowej" },
    ],
    objects: [
      { id: "building", kind: "obstacle", rect: { x: 680, y: 0, w: 920, h: 480 } },
      { id: "trees", kind: "obstacle", rect: { x: 0, y: 0, w: 680, h: 570 } },
      { id: "shed", kind: "obstacle", rect: { x: 540, y: 604, w: 315, h: 125 } },
      { id: "cars", kind: "obstacle", rect: { x: 396, y: 729, w: 437, h: 171 } },
      { id: "i-treat1", kind: "item", itemId: "treat", rect: { x: 1000, y: 750, w: 50, h: 50 } },
      { id: "i-treat2", kind: "item", itemId: "treat", rect: { x: 1350, y: 650, w: 50, h: 50 } },
      { id: "i-treat3", kind: "item", itemId: "treat", rect: { x: 850, y: 550, w: 50, h: 50 } },
      { id: "pigeon", kind: "npc", npcId: "pigeon", icon: "🐦", rect: { x: 950, y: 580, w: 70, h: 70 },
        message: "Gruchanie! Gołąb podaje Edkowi błyszczące piórko." },
      { id: "entrance", kind: "goal", icon: "🚪", rect: { x: 900, y: 420, w: 100, h: 60 },
        requires: { treat: 3, feather: 1 }, message: "Klatka schodowa! Edek wraca do domu po wielkiej wyprawie." },
    ],
  },
];

export const getLevel = (id: string): LevelDef | undefined => LEVELS.find((l) => l.id === id);
