import type { LevelDef } from "./types";
import walyBg from "@/assets/waly-merged.jpeg";
import park1Bg from "@/assets/park-merged.jpeg";
import park2Bg from "@/assets/alley-merged.jpeg";
import atticBg from "@/assets/level-attic.jpg";
import gardenBg from "@/assets/level-garden.jpg";
import lucznBg from "@/assets/lu.jpeg";

const W = 1600;
const H = 900;

export const LEVELS: LevelDef[] = [
  {
    id: "1",
    slug: "waly-chrobrego",
    title: "Wały Chrobrego",
    subtitle: "Wieczorny spacer nad Odrą",
    background: walyBg,
    width: 3200,
    height: 900,
    spawn: { x: 400, y: 650 },
    ambient: "night",
    ambientFx: "motes",
    // Sepia-warm evening with a firefly-like glow around the promenade lamps
    // (the "motes" ambientFx + pointLight above already do the glow itself —
    // this just tints the whole scene to match).
    mood: { sepia: true, brightness: 1.0, contrast: 1.08, saturate: 0.05, hue: 8 },
    intro: "Wieczorne światła Wałów Chrobrego migoczą nad Odrą. Edek wymyka się na spacer.",
    objective: "Znajdź piłeczkę i smakołyk, potem wejdź przez bramę do baszty.",
    unlockHint: "Dostępne od początku — pierwsza wyprawa Edka.",
    quests: [
      {
        id: "q1-ball",
        kind: "collect",
        itemId: "ball",
        count: 1,
        label: "Znajdź piłeczkę na promenadzie",
      },
      {
        id: "q1-treat",
        kind: "collect",
        itemId: "treat",
        count: 1,
        label: "Znajdź smakołyk przy latarni",
      },
      { id: "q1-entrance", kind: "reach", objId: "entrance", label: "Wejdź przez bramę do baszty" },
    ],
    pointLight: { x: 750, y: 450, color: "rgba(255,180,80,0.85)", intensity: 0.7 },
    objects: [
      { id: "building", kind: "obstacle", rect: { x: 480, y: 0, w: 650, h: 330 } },
      { id: "amphitheater", kind: "obstacle", rect: { x: 680, y: 520, w: 420, h: 280 } },
      { id: "trees-left", kind: "obstacle", rect: { x: 0, y: 0, w: 230, h: 900 } },
      { id: "trees-right", kind: "obstacle", rect: { x: 1450, y: 0, w: 150, h: 600 } },
      { id: "building2", kind: "obstacle", rect: { x: 2550, y: 0, w: 650, h: 600 } },
      { id: "trees-right-edge", kind: "obstacle", rect: { x: 3100, y: 0, w: 100, h: 900 } },
      { id: "river", kind: "obstacle", rect: { x: 0, y: 800, w: 3200, h: 100 } },
      { id: "i-ball", kind: "item", itemId: "ball", rect: { x: 320, y: 430, w: 50, h: 50 } },
      { id: "i-treat", kind: "item", itemId: "treat", rect: { x: 2350, y: 700, w: 50, h: 50 } },
      // Optional collectible (Photographer mode) — not required by any quest.
      {
        id: "i-photo",
        kind: "item",
        itemId: "photo",
        icon: "📷",
        rect: { x: 1700, y: 700, w: 50, h: 50 },
      },
      {
        id: "entrance",
        kind: "goal",
        icon: "🏰",
        rect: { x: 2500, y: 610, w: 120, h: 80 },
        requires: { ball: 1, treat: 1 },
        message: "Brama otwarta! Edek wchodzi do baszty pełnej tajemnic.",
      },
    ],
  },
  {
    id: "2",
    slug: "park-kasprowicza",
    title: "Park Kasprowicza",
    subtitle: "Pomnik Czynu Polaków",
    background: park1Bg,
    width: 3200,
    height: 900,
    spawn: { x: 300, y: 700 },
    ambient: "day",
    ambientFx: "petals",
    // Rich, saturated park greens — the lushest-looking level.
    mood: { brightness: 1.03, contrast: 1.04, saturate: 0.3, hue: -4 },
    intro: "Słońce grzeje klomby przy Pomniku Czynu Polaków. Edek węszy wśród kwiatów.",
    objective: "Znajdź 3 myszki, pogadaj z wiewiórką, znajdź wyjście w głąb alei.",
    unlockHint: "Odblokowane po wieczornym spacerze na Wałach Chrobrego (Poziom 1).",
    quests: [
      {
        id: "q2-mice",
        kind: "collect",
        itemId: "mouse",
        count: 3,
        label: "Znajdź 3 myszki na trawnikach parku",
      },
      {
        id: "q2-squirrel",
        kind: "talk",
        objId: "squirrel",
        label: "Pogadaj z wiewiórką przy pomniku",
      },
      { id: "q2-gate", kind: "reach", objId: "gate", label: "Znajdź wyjście w głąb alei" },
    ],
    objects: [
      { id: "tree", kind: "obstacle", rect: { x: 100, y: 0, w: 480, h: 420 } },
      { id: "monument", kind: "obstacle", rect: { x: 680, y: 180, w: 200, h: 220 } },
      { id: "bushes-right", kind: "obstacle", rect: { x: 1350, y: 0, w: 250, h: 500 } },
      { id: "bushes-bottom-right", kind: "obstacle", rect: { x: 1300, y: 600, w: 300, h: 300 } },
      { id: "center-tree2", kind: "obstacle", rect: { x: 2300, y: 150, w: 450, h: 550 } },
      { id: "trees-right-edge", kind: "obstacle", rect: { x: 3100, y: 0, w: 100, h: 900 } },
      { id: "m1", kind: "item", itemId: "mouse", rect: { x: 200, y: 500, w: 50, h: 50 } },
      { id: "m2", kind: "item", itemId: "mouse", rect: { x: 1100, y: 300, w: 50, h: 50 } },
      { id: "m3", kind: "item", itemId: "mouse", rect: { x: 600, y: 750, w: 50, h: 50 } },
      {
        id: "squirrel",
        kind: "npc",
        npcId: "squirrel",
        icon: "🐿️",
        rect: { x: 450, y: 440, w: 80, h: 80 },
        message: "Cześć Edku! Weź ten kłębek — przyda Ci się.",
        patrol: { range: 140, speed: 26 },
      },
      {
        id: "i-photo",
        kind: "item",
        itemId: "photo",
        icon: "📷",
        rect: { x: 1800, y: 200, w: 50, h: 50 },
      },
      {
        id: "gate",
        kind: "goal",
        icon: "🚪",
        rect: { x: 2900, y: 400, w: 100, h: 90 },
        requires: { mouse: 3, yarn: 1 },
        message: "Aleja prowadzi dalej. Czas na złote liście!",
      },
    ],
  },
  {
    id: "3",
    slug: "aleja-kasztanowa",
    title: "Aleja Kasztanowa",
    subtitle: "Złota jesień w Parku Kasprowicza",
    background: park2Bg,
    width: 3200,
    height: 900,
    spawn: { x: 800, y: 800 },
    ambient: "day",
    ambientFx: "petals",
    // Golden hour: warm orange hue push, slightly boosted contrast.
    mood: { brightness: 1.06, contrast: 1.06, saturate: 0.12, hue: 14 },
    intro: "Złota aleja szeleści pod łapkami. Edek brnie przez stertę liści.",
    objective: "Zbierz 3 złote liście i odpocznij na ławce.",
    unlockHint: "Odblokowane po zwiedzeniu Pomnika Czynu Polaków (Poziom 2).",
    quests: [
      {
        id: "q3-leaves",
        kind: "collect",
        itemId: "leaf",
        count: 3,
        label: "Zbierz 3 złote liście",
      },
      { id: "q3-bench", kind: "reach", objId: "bench", label: "Zwiń się w kłębek na ławce" },
    ],
    objects: [
      { id: "center-tree", kind: "obstacle", rect: { x: 600, y: 0, w: 420, h: 340 } },
      { id: "flowerbed-l", kind: "obstacle", rect: { x: 280, y: 340, w: 280, h: 220 } },
      { id: "flowerbed-r", kind: "obstacle", rect: { x: 1040, y: 340, w: 280, h: 220 } },
      { id: "center-tree2", kind: "obstacle", rect: { x: 2300, y: 150, w: 450, h: 550 } },
      { id: "trees-right-edge", kind: "obstacle", rect: { x: 3100, y: 0, w: 100, h: 900 } },
      { id: "i-leaf1", kind: "item", itemId: "leaf", rect: { x: 400, y: 700, w: 50, h: 50 } },
      { id: "i-leaf2", kind: "item", itemId: "leaf", rect: { x: 2600, y: 700, w: 50, h: 50 } },
      { id: "i-leaf3", kind: "item", itemId: "leaf", rect: { x: 800, y: 450, w: 50, h: 50 } },
      {
        id: "i-photo",
        kind: "item",
        itemId: "photo",
        icon: "📷",
        rect: { x: 1800, y: 300, w: 50, h: 50 },
      },
      {
        id: "bench",
        kind: "goal",
        icon: "🍂",
        rect: { x: 720, y: 830, w: 160, h: 70 },
        requires: { leaf: 3 },
        message: "Edek zwija się w kłębek na ławce, otoczony jesiennymi liśćmi.",
      },
    ],
  },
  {
    id: "4",
    slug: "dach",
    title: "Strych o zmroku",
    subtitle: "Zakurzone tajemnice pod dachem",
    background: atticBg,
    width: W,
    height: H,
    spawn: { x: 780, y: 600 },
    ambient: "night",
    ambientFx: "stars",
    // Cool nighttime blue — a chillier grade than the generic night blend.
    mood: { brightness: 0.88, contrast: 1.1, saturate: -0.08, hue: -14, vignetteStrength: 0.42 },
    intro: "Powietrze jest chłodne. Zakurzony strych skrzypi w ciszy, oświetlony jedną lampą.",
    objective: "Zbierz 5 spadających gwiazd i spotkaj się z przyjacielem.",
    unlockHint: "Odblokowane po jesiennym spacerze Aleją Kasztanową (Poziom 3).",
    quests: [
      {
        id: "q4-stars",
        kind: "collect",
        itemId: "star",
        count: 5,
        label: "Zbierz 5 spadających gwiazd",
      },
      { id: "q4-friend", kind: "reach", objId: "friend", label: "Znajdź przyjaciela na dachu" },
    ],
    objects: [
      { id: "back-wall", kind: "obstacle", rect: { x: 0, y: 0, w: 1600, h: 317 } },
      { id: "chest-cluster-left", kind: "obstacle", rect: { x: 233, y: 708, w: 458, h: 192 } },
      { id: "chest-cluster-right", kind: "obstacle", rect: { x: 875, y: 708, w: 500, h: 192 } },
      { id: "s1", kind: "item", itemId: "star", rect: { x: 600, y: 480, w: 50, h: 50 } },
      { id: "s2", kind: "item", itemId: "star", rect: { x: 900, y: 430, w: 50, h: 50 } },
      { id: "s3", kind: "item", itemId: "star", rect: { x: 1200, y: 550, w: 50, h: 50 } },
      { id: "s4", kind: "item", itemId: "star", rect: { x: 480, y: 650, w: 50, h: 50 } },
      { id: "s5", kind: "item", itemId: "star", rect: { x: 1100, y: 680, w: 50, h: 50 } },
      {
        id: "i-photo",
        kind: "item",
        itemId: "photo",
        icon: "📷",
        rect: { x: 350, y: 550, w: 50, h: 50 },
      },
      {
        id: "friend",
        kind: "goal",
        icon: "🐈",
        rect: { x: 710, y: 800, w: 160, h: 80 },
        requires: { star: 5 },
        message: "Przyjaciel mruczy: 'Wiedziałem, że dasz radę, Edek!'",
      },
    ],
  },
  {
    id: "5",
    slug: "blokowisko",
    title: "Ogród za blokiem",
    subtitle: "Zielony zakątek w Szczecinie",
    background: gardenBg,
    width: W,
    height: H,
    spawn: { x: 750, y: 850 },
    ambient: "day",
    // Overcast blokowisko courtyard: drifting dust, not fireflies/petals.
    ambientFx: "dust",
    // Overcast: flattened contrast, muted saturation, no warm hue push.
    mood: { brightness: 0.97, contrast: 0.94, saturate: -0.18, hue: 0 },
    intro: "Ktoś zostawił furtkę do ogrodu za blokiem uchyloną. Edek wymyka się między kwietniki.",
    objective: "Znajdź 3 smakołyki, pogadaj z gołębiem, wróć do klatki schodowej.",
    unlockHint: "Odblokowane po powrocie z dachu (Poziom 4).",
    quests: [
      {
        id: "q5-treats",
        kind: "collect",
        itemId: "treat",
        count: 3,
        label: "Znajdź 3 smakołyki na podwórku",
      },
      { id: "q5-pigeon", kind: "talk", objId: "pigeon", label: "Pogadaj z gołębiem po piórko" },
      { id: "q5-entrance", kind: "reach", objId: "entrance", label: "Wróć do klatki schodowej" },
    ],
    objects: [
      { id: "trees-topleft", kind: "obstacle", rect: { x: 0, y: 0, w: 417, h: 375 } },
      { id: "trees-topright", kind: "obstacle", rect: { x: 1292, y: 0, w: 308, h: 417 } },
      { id: "bushes-left", kind: "obstacle", rect: { x: 0, y: 333, w: 417, h: 333 } },
      { id: "bushes-bottomleft", kind: "obstacle", rect: { x: 208, y: 625, w: 417, h: 275 } },
      { id: "pond", kind: "obstacle", rect: { x: 1083, y: 625, w: 517, h: 275 } },
      { id: "bushes-right", kind: "obstacle", rect: { x: 1292, y: 125, w: 308, h: 333 } },
      { id: "i-treat1", kind: "item", itemId: "treat", rect: { x: 700, y: 500, w: 50, h: 50 } },
      { id: "i-treat2", kind: "item", itemId: "treat", rect: { x: 950, y: 650, w: 50, h: 50 } },
      { id: "i-treat3", kind: "item", itemId: "treat", rect: { x: 750, y: 750, w: 50, h: 50 } },
      {
        id: "pigeon",
        kind: "npc",
        npcId: "pigeon",
        icon: "🐦",
        rect: { x: 1000, y: 450, w: 70, h: 70 },
        message: "Gruchanie! Gołąb podaje Edkowi błyszczące piórko.",
        patrol: { range: 180, speed: 34 },
      },
      {
        id: "i-photo",
        kind: "item",
        itemId: "photo",
        icon: "📷",
        rect: { x: 650, y: 350, w: 50, h: 50 },
      },
      {
        id: "entrance",
        kind: "goal",
        icon: "🚪",
        rect: { x: 700, y: 80, w: 150, h: 90 },
        requires: { treat: 3, feather: 1 },
        message: "Klatka schodowa! Edek wraca do domu po wielkiej wyprawie.",
      },
    ],
  },
  {
    id: "6",
    slug: "lucznicza-43",
    title: "Łucznicza 43",
    subtitle: "Nowe podwórko w Szczecinie",
    background: lucznBg,
    width: 1600,
    height: 1200,
    spawn: { x: 120, y: 1050 },
    ambient: "day",
    ambientFx: "dust",
    // Morning golden hour: softer/warmer than Aleja's late-afternoon gold.
    mood: { brightness: 1.05, contrast: 1.02, saturate: 0.08, hue: 10 },
    intro: "Edek trafia na podwórko przy Łuczniczej 43 — zupełnie nowe sąsiedztwo do obwąchania.",
    objective: "Znajdź 3 miski z karmą, pogadaj z sąsiadem kotem, wróć do klatki schodowej.",
    unlockHint: "Odblokowane po powrocie z podwórka na Blokowisku (Poziom 5).",
    quests: [
      {
        id: "q6-bowls",
        kind: "collect",
        itemId: "bowl",
        count: 3,
        label: "Znajdź 3 miski z karmą na podwórku",
      },
      { id: "q6-cat", kind: "talk", objId: "kot", label: "Pogadaj z sąsiadem kotem" },
      { id: "q6-entrance", kind: "reach", objId: "entrance", label: "Wróć do klatki schodowej" },
    ],
    objects: [
      { id: "building-main", kind: "obstacle", rect: { x: 220, y: 100, w: 1000, h: 430 } },
      { id: "building-annex", kind: "obstacle", rect: { x: 1180, y: 200, w: 400, h: 670 } },
      { id: "trees-topleft", kind: "obstacle", rect: { x: 0, y: 0, w: 180, h: 360 } },
      { id: "trees-left", kind: "obstacle", rect: { x: 0, y: 400, w: 230, h: 500 } },
      { id: "i-bowl1", kind: "item", itemId: "bowl", rect: { x: 300, y: 950, w: 50, h: 50 } },
      { id: "i-bowl2", kind: "item", itemId: "bowl", rect: { x: 900, y: 1000, w: 50, h: 50 } },
      { id: "i-bowl3", kind: "item", itemId: "bowl", rect: { x: 1350, y: 1000, w: 50, h: 50 } },
      {
        id: "kot",
        kind: "npc",
        npcId: "kot",
        icon: "🐈",
        rect: { x: 250, y: 550, w: 70, h: 70 },
        message: "Mruczenie! Sąsiedzki kocur podaje Edkowi zapasowy klucz do klatki.",
      },
      {
        id: "i-photo",
        kind: "item",
        itemId: "photo",
        icon: "📷",
        rect: { x: 700, y: 1100, w: 50, h: 50 },
      },
      {
        id: "entrance",
        kind: "goal",
        icon: "🚪",
        rect: { x: 560, y: 480, w: 120, h: 80 },
        requires: { bowl: 3, key: 1 },
        message: "Klatka schodowa przy Łuczniczej 43! Edek wraca do domu.",
      },
    ],
  },
];

export const getLevel = (id: string): LevelDef | undefined => LEVELS.find((l) => l.id === id);
