import type { LevelDef } from "./types";
import salonBg from "@/assets/level-salon.jpg";
import gardenBg from "@/assets/level-garden.jpg";
import atticBg from "@/assets/level-attic.jpg";
import roofBg from "@/assets/level-roof.jpg";
import blokBg from "@/assets/level-blok.jpg";

const W = 1600;
const H = 900;

export const LEVELS: LevelDef[] = [
  {
    id: "1",
    slug: "salon",
    title: "Salon",
    subtitle: "Poranna pobudka",
    background: salonBg,
    width: W,
    height: H,
    spawn: { x: 200, y: 700 },
    ambient: "day",
    ambientFx: "motes",
    intro: "Edek otwiera jedno oko. Pachnie chrupkami i drewnem kominka.",
    objective: "Znajdź miskę i piłeczkę, potem podejdź do drzwi.",
    unlockHint: "Dostępne od początku — to dom Edka.",
    quests: [
      { id: "q1-bowl", kind: "collect", itemId: "bowl", count: 1, label: "Znajdź miskę" },
      { id: "q1-ball", kind: "collect", itemId: "ball", count: 1, label: "Znajdź piłeczkę" },
      { id: "q1-door", kind: "reach", objId: "door", label: "Wyjdź drzwiami do ogrodu" },
    ],
    pointLight: { x: 800, y: 180, color: "rgba(255,140,60,0.8)", intensity: 0.6 },
    objects: [
      { id: "sofa", kind: "obstacle", rect: { x: 600, y: 100, w: 400, h: 220 } },
      { id: "table", kind: "obstacle", rect: { x: 720, y: 320, w: 160, h: 140 } },
      { id: "armchair", kind: "obstacle", rect: { x: 480, y: 280, w: 120, h: 120 } },
      { id: "shelf", kind: "obstacle", rect: { x: 60, y: 100, w: 140, h: 350 } },
      { id: "shelf2", kind: "obstacle", rect: { x: 1400, y: 100, w: 140, h: 400 } },
      { id: "i-bowl", kind: "item", itemId: "bowl", rect: { x: 1300, y: 720, w: 60, h: 60 } },
      { id: "i-ball", kind: "item", itemId: "ball", rect: { x: 300, y: 380, w: 50, h: 50 } },
      { id: "door", kind: "goal", icon: "🚪", rect: { x: 760, y: 820, w: 120, h: 60 },
        requires: { bowl: 1, ball: 1 }, message: "Drzwi otwarte! Wyrusz do ogrodu." },
    ],
  },
  {
    id: "2",
    slug: "ogrod",
    title: "Ogród",
    subtitle: "Słońce i pszczoły",
    background: gardenBg,
    width: W,
    height: H,
    spawn: { x: 200, y: 200 },
    ambient: "day",
    ambientFx: "petals",
    intro: "Trawa łaskocze łapki. Gdzieś brzęczy pszczoła.",
    objective: "Znajdź 3 myszki, pogadaj z wiewiórką, dojdź do bramy.",
    unlockHint: "Odblokowane po wyjściu z salonu (Poziom 1).",
    quests: [
      { id: "q2-mice", kind: "collect", itemId: "mouse", count: 3, label: "Złap 3 myszki w trawie" },
      { id: "q2-squirrel", kind: "talk", objId: "squirrel", label: "Pogadaj z wiewiórką po kłębek" },
      { id: "q2-gate", kind: "reach", objId: "gate", label: "Dojdź do bramy ogrodu" },
    ],
    objects: [
      { id: "pond", kind: "obstacle", rect: { x: 1200, y: 600, w: 380, h: 280 } },
      { id: "tree1", kind: "obstacle", rect: { x: 1380, y: 60, w: 200, h: 180 } },
      { id: "stump", kind: "obstacle", rect: { x: 820, y: 380, w: 130, h: 110 } },
      { id: "bush", kind: "obstacle", rect: { x: 100, y: 700, w: 220, h: 180 } },
      { id: "m1", kind: "item", itemId: "mouse", rect: { x: 700, y: 80, w: 50, h: 50 } },
      { id: "m2", kind: "item", itemId: "mouse", rect: { x: 1080, y: 470, w: 50, h: 50 } },
      { id: "m3", kind: "item", itemId: "mouse", rect: { x: 420, y: 800, w: 50, h: 50 } },
      { id: "bee1", kind: "trigger", danger: true, rect: { x: 500, y: 200, w: 120, h: 120 },
        message: "Pszczoła! Edek traci energię." },
      { id: "bee2", kind: "trigger", danger: true, rect: { x: 1000, y: 250, w: 120, h: 120 },
        message: "Bzz! Uważaj na pszczoły!" },
      { id: "squirrel", kind: "npc", npcId: "squirrel", icon: "🐿️", rect: { x: 1440, y: 340, w: 80, h: 80 },
        message: "Cześć Edku! Weź ten kłębek — przyda Ci się." },
      { id: "gate", kind: "goal", icon: "🚪", rect: { x: 1500, y: 420, w: 80, h: 100 },
        requires: { mouse: 3, yarn: 1 }, message: "Brama otwarta. Czas na strych!" },
    ],
  },
  {
    id: "3",
    slug: "strych",
    title: "Strych",
    subtitle: "Kurz i tajemnice",
    background: atticBg,
    width: W,
    height: H,
    spawn: { x: 300, y: 600 },
    ambient: "dim",
    ambientFx: "dust",
    intro: "Ciemno. Tylko mała plama światła pod stopami.",
    objective: "Znajdź klucz i otwórz starą skrzynię.",
    unlockHint: "Odblokowane po przejściu Ogrodu (Poziom 2).",
    quests: [
      { id: "q3-key", kind: "collect", itemId: "key", count: 1, label: "Znajdź zardzewiały klucz" },
      { id: "q3-chest", kind: "reach", objId: "i-chest", label: "Otwórz starą skrzynię" },
    ],
    objects: [
      { id: "dresser", kind: "obstacle", rect: { x: 700, y: 100, w: 360, h: 250 } },
      { id: "boxes1", kind: "obstacle", rect: { x: 540, y: 180, w: 140, h: 170 } },
      { id: "sheets1", kind: "obstacle", rect: { x: 200, y: 130, w: 280, h: 260 } },
      { id: "sheets2", kind: "obstacle", rect: { x: 1100, y: 130, w: 250, h: 270 } },
      { id: "sheets3", kind: "obstacle", rect: { x: 1370, y: 130, w: 200, h: 270 } },
      { id: "lamp", kind: "obstacle", rect: { x: 60, y: 480, w: 130, h: 200 } },
      { id: "i-key", kind: "item", itemId: "key", rect: { x: 1500, y: 750, w: 50, h: 50 } },
      { id: "i-chest", kind: "goal", icon: "🧰", rect: { x: 560, y: 800, w: 200, h: 80 },
        requires: { key: 1 }, message: "Skrzynia otwarta. W środku stara fotografia." },
    ],
  },
  {
    id: "4",
    slug: "dach",
    title: "Dach nocą",
    subtitle: "Pod gwiazdami",
    background: roofBg,
    width: W,
    height: H,
    spawn: { x: 200, y: 800 },
    ambient: "night",
    ambientFx: "stars",
    intro: "Powietrze jest chłodne. Księżyc wisi tuż obok.",
    objective: "Zbierz 5 spadających gwiazd i spotkaj się z przyjacielem.",
    unlockHint: "Odblokowane po odkryciu sekretu na Strychu (Poziom 3).",
    quests: [
      { id: "q4-stars", kind: "collect", itemId: "star", count: 5, label: "Zbierz 5 spadających gwiazd" },
      { id: "q4-friend", kind: "reach", objId: "friend", label: "Znajdź przyjaciela na dachu" },
    ],
    objects: [
      { id: "chimney1", kind: "obstacle", rect: { x: 480, y: 240, w: 180, h: 200 } },
      { id: "chimney2", kind: "obstacle", rect: { x: 1180, y: 540, w: 180, h: 220 } },
      { id: "vane", kind: "obstacle", rect: { x: 900, y: 380, w: 120, h: 200 } },
      { id: "s1", kind: "item", itemId: "star", rect: { x: 300, y: 200, w: 50, h: 50 } },
      { id: "s2", kind: "item", itemId: "star", rect: { x: 800, y: 100, w: 50, h: 50 } },
      { id: "s3", kind: "item", itemId: "star", rect: { x: 1300, y: 250, w: 50, h: 50 } },
      { id: "s4", kind: "item", itemId: "star", rect: { x: 700, y: 700, w: 50, h: 50 } },
      { id: "s5", kind: "item", itemId: "star", rect: { x: 1450, y: 800, w: 50, h: 50 } },
      { id: "friend", kind: "goal", icon: "🐈", rect: { x: 1400, y: 400, w: 100, h: 100 },
        requires: { star: 5 }, message: "Przyjaciel mruczy: 'Wiedziałem, że dasz radę, Edek!'" },
    ],
  },
  {
    id: "5",
    slug: "blokowisko",
    title: "Blokowisko",
    subtitle: "Wielka wyprawa w Szczecinie",
    background: blokBg,
    width: W,
    height: H,
    spawn: { x: 150, y: 800 },
    ambient: "day",
    ambientFx: "motes",
    intro: "Ktoś zostawił okno na klatce uchylone. Edek zeskakuje na podwórko — ale skąd tu wraca do domu?",
    objective: "Znajdź 3 smakołyki, pogadaj z gołębiem, wróć do klatki schodowej.",
    unlockHint: "Odblokowane po powrocie z dachu (Poziom 4).",
    quests: [
      { id: "q5-treats", kind: "collect", itemId: "treat", count: 3, label: "Znajdź 3 smakołyki na podwórku" },
      { id: "q5-pigeon", kind: "talk", objId: "pigeon", label: "Pogadaj z gołębiem po piórko" },
      { id: "q5-entrance", kind: "reach", objId: "entrance", label: "Wróć do klatki schodowej" },
    ],
    objects: [
      { id: "building", kind: "obstacle", rect: { x: 680, y: 0, w: 920, h: 480 } },
      { id: "trees", kind: "obstacle", rect: { x: 0, y: 0, w: 680, h: 570 } },
      { id: "shed", kind: "obstacle", rect: { x: 540, y: 604, w: 315, h: 125 } },
      { id: "cars", kind: "obstacle", rect: { x: 396, y: 729, w: 437, h: 171 } },
      { id: "i-treat1", kind: "item", itemId: "treat", rect: { x: 1000, y: 750, w: 50, h: 50 } },
      { id: "i-treat2", kind: "item", itemId: "treat", rect: { x: 1350, y: 650, w: 50, h: 50 } },
      { id: "i-treat3", kind: "item", itemId: "treat", rect: { x: 850, y: 550, w: 50, h: 50 } },
      { id: "pigeon", kind: "npc", npcId: "pigeon", icon: "🐦", rect: { x: 950, y: 580, w: 70, h: 70 },
        message: "Gruchanie! Gołąb podaje Edkowi błyszczące piórko." },
      { id: "entrance", kind: "goal", icon: "🚪", rect: { x: 900, y: 420, w: 100, h: 60 },
        requires: { treat: 3, feather: 1 }, message: "Klatka schodowa! Edek wraca do domu po wielkiej wyprawie." },
    ],
  },
];

export const getLevel = (id: string): LevelDef | undefined => LEVELS.find((l) => l.id === id);
