/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UstawieniaRouteImport } from './routes/ustawienia'
import { Route as Poziom3dRouteImport } from './routes/poziom3d'
import { Route as OsiagnieciaRouteImport } from './routes/osiagniecia'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as KoniecRouteImport } from './routes/koniec'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PoziomIdRouteImport } from './routes/poziom.$id'

const UstawieniaRoute = UstawieniaRouteImport.update({
  id: '/ustawienia',
  path: '/ustawienia',
  getParentRoute: () => rootRouteImport,
} as any)
const Poziom3dRoute = Poziom3dRouteImport.update({
  id: '/poziom3d',
  path: '/poziom3d',
  getParentRoute: () => rootRouteImport,
} as any)
const OsiagnieciaRoute = OsiagnieciaRouteImport.update({
  id: '/osiagniecia',
  path: '/osiagniecia',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const KoniecRoute = KoniecRouteImport.update({
  id: '/koniec',
  path: '/koniec',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PoziomIdRoute = PoziomIdRouteImport.update({
  id: '/poziom/$id',
  path: '/poziom/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/koniec': typeof KoniecRoute
  '/menu': typeof MenuRoute
  '/osiagniecia': typeof OsiagnieciaRoute
  '/poziom3d': typeof Poziom3dRoute
  '/ustawienia': typeof UstawieniaRoute
  '/poziom/$id': typeof PoziomIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/koniec': typeof KoniecRoute
  '/menu': typeof MenuRoute
  '/osiagniecia': typeof OsiagnieciaRoute
  '/poziom3d': typeof Poziom3dRoute
  '/ustawienia': typeof UstawieniaRoute
  '/poziom/$id': typeof PoziomIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/koniec': typeof KoniecRoute
  '/menu': typeof MenuRoute
  '/osiagniecia': typeof OsiagnieciaRoute
  '/poziom3d': typeof Poziom3dRoute
  '/ustawienia': typeof UstawieniaRoute
  '/poziom/$id': typeof PoziomIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/koniec'
    | '/menu'
    | '/osiagniecia'
    | '/poziom3d'
    | '/ustawienia'
    | '/poziom/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/koniec'
    | '/menu'
    | '/osiagniecia'
    | '/poziom3d'
    | '/ustawienia'
    | '/poziom/$id'
  id:
    | '__root__'
    | '/'
    | '/koniec'
    | '/menu'
    | '/osiagniecia'
    | '/poziom3d'
    | '/ustawienia'
    | '/poziom/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KoniecRoute: typeof KoniecRoute
  MenuRoute: typeof MenuRoute
  OsiagnieciaRoute: typeof OsiagnieciaRoute
  Poziom3dRoute: typeof Poziom3dRoute
  UstawieniaRoute: typeof UstawieniaRoute
  PoziomIdRoute: typeof PoziomIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ustawienia': {
      id: '/ustawienia'
      path: '/ustawienia'
      fullPath: '/ustawienia'
      preLoaderRoute: typeof UstawieniaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poziom3d': {
      id: '/poziom3d'
      path: '/poziom3d'
      fullPath: '/poziom3d'
      preLoaderRoute: typeof Poziom3dRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/osiagniecia': {
      id: '/osiagniecia'
      path: '/osiagniecia'
      fullPath: '/osiagniecia'
      preLoaderRoute: typeof OsiagnieciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/koniec': {
      id: '/koniec'
      path: '/koniec'
      fullPath: '/koniec'
      preLoaderRoute: typeof KoniecRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poziom/$id': {
      id: '/poziom/$id'
      path: '/poziom/$id'
      fullPath: '/poziom/$id'
      preLoaderRoute: typeof PoziomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KoniecRoute: KoniecRoute,
  MenuRoute: MenuRoute,
  OsiagnieciaRoute: OsiagnieciaRoute,
  Poziom3dRoute: Poziom3dRoute,
  UstawieniaRoute: UstawieniaRoute,
  PoziomIdRoute: PoziomIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
